import pandas as pd
import io
from shapely.geometry import Point, Polygon, shape
import geopandas as gpd

class BKDReportGenerator:
    """
    Generates multi-sheet Excel reports for BKD PAD Monitoring.
    Creates 3-way tables (pivot tables) aggregating data by administrative boundaries.
    """
    
    def __init__(self, boundary_mgr):
        self.boundary_mgr = boundary_mgr
        
    def _enrich_with_admin_info(self, data_list, lat_key='lat', lon_key='lon', polygon_key=None):
        """
        Enrich a list of dictionaries with Kecamatan, Kelurahan, Lingkungan info
        by performing a spatial join with the boundary data.
        """
        if not data_list or self.boundary_mgr is None or self.boundary_mgr._gdf is None:
            return pd.DataFrame(data_list)
            
        # Create GeoDataFrame from data_list
        geometries = []
        for item in data_list:
            if polygon_key and item.get(polygon_key):
                # If polygon coordinates are available
                try:
                    coords = item[polygon_key]
                    # Ensure coords are in (lon, lat) format for Shapely
                    # Input might be [(lat, lon), ...] or [(lon, lat), ...] depending on source
                    # Checking common patterns. Usually Folium uses (lat, lon). GeoJSON (lon, lat).
                    # Let's assume standard (lon, lat) if generated by geometry engines, 
                    # but check if we need to swap.
                    # Based on existing code (folium_coords = [[c[1], c[0]]...]), the internal data seems to be (lon, lat) or (lat, lon)?
                    # Converting based on field names usually safest.
                    
                    # Safe bet: use centroid from lat/lon keys if available
                    if lat_key in item and lon_key in item:
                         geometries.append(Point(item[lon_key], item[lat_key]))
                    else:
                        # Fallback to first point of polygon
                        geometries.append(Point(coords[0][0], coords[0][1])) 
                except:
                    geometries.append(None)
            elif lat_key in item and lon_key in item:
                geometries.append(Point(item[lon_key], item[lat_key]))
            else:
                geometries.append(None)
                
        df = pd.DataFrame(data_list)
        gdf_data = gpd.GeoDataFrame(df, geometry=geometries, crs="EPSG:4326")
        
        # Perform spatial join
        # We want to attach info from boundary_mgr._gdf to our data
        # _gdf has columns: 'nmkec', 'nmdesa', 'nmsls'
        
        try:
            # Clean dictionary keys from DataFrame that might conflict or be complex objects
            cols_to_drop = [c for c in gdf_data.columns if isinstance(gdf_data[c].iloc[0], (dict, list)) and c not in ['geometry']]
            # Actually keep them, pandas can handle objects.
            
            joined = gpd.sjoin(gdf_data, self.boundary_mgr._gdf[['nmkec', 'nmdesa', 'nmsls', 'geometry']], how="left", predicate="within")
            
            # Formatting admin columns
            joined['Kecamatan'] = joined['nmkec'].fillna('Unknown')
            joined['Kelurahan'] = joined['nmdesa'].fillna('Unknown')
            
            # Parse Lingkungan from nmsls
            def extract_lingkungan(nmsls):
                if pd.isna(nmsls): return 'Unknown'
                if 'LINGKUNGAN' in str(nmsls):
                    parts = str(nmsls).split(' LINGKUNGAN ')
                    return parts[1].strip() if len(parts) > 1 else str(nmsls)
                return str(nmsls)
                
            joined['Lingkungan'] = joined['nmsls'].apply(extract_lingkungan)
            
            return pd.DataFrame(joined.drop(columns=['geometry', 'index_right', 'nmkec', 'nmdesa', 'nmsls']))
            
        except Exception as e:
            print(f"Spatial join failed: {e}")
            # Return original df with empty admin cols
            df['Kecamatan'] = 'Unknown'
            df['Kelurahan'] = 'Unknown'
            df['Lingkungan'] = 'Unknown'
            return df

    def generate_excel(self, parking_data, landuse_data, pbb_data, years_info=None):
        output = io.BytesIO()
        writer = pd.ExcelWriter(output, engine='openpyxl')
        
        # 1. Summary Sheet
        self._create_summary_sheet(writer, parking_data, landuse_data, pbb_data, years_info)
        
        # 2. Parking Analysis (3-Way)
        if parking_data and 'parking_areas' in parking_data:
            df_parking = self._enrich_with_admin_info(parking_data['parking_areas'])
            self._create_parking_sheet(writer, df_parking, years_info)
            
        # 3. Land Use (3-Way)
        if landuse_data and 'changes' in landuse_data:
            df_landuse = self._enrich_with_admin_info(landuse_data['changes'])
            self._create_landuse_sheet(writer, df_landuse, years_info)
            
        # 4. PBB Monitoring (3-Way)
        if pbb_data and 'changes' in pbb_data:
            df_pbb = self._enrich_with_admin_info(pbb_data['changes'])
            self._create_pbb_sheet(writer, df_pbb, years_info)
            
        writer.close()
        return output.getvalue()

    def _create_summary_sheet(self, writer, parking, landuse, pbb, years_info):
        """Create executive summary sheet"""
        
        period_str = f"{years_info.get('start', '-')} - {years_info.get('end', '-')}" if years_info else "Periode tidak spesifik"
        
        summary_data = {
            'Aura Analisis': [
                'Periode Analisis',
                'Total Potensi Parkir (Rp/Tahun)',
                'Total Potensi Pajak Alih Fungsi (Rp)',
                'Total Kenaikan PBB (Rp/Tahun)', 
                'TOTAL POTENSI PAD (Rp)'
            ],
            'Nilai': [
                period_str,
                parking.get('estimated_revenue_annual', 0) if parking else 0,
                landuse.get('tax_potential', {}).get('total_annual', 0) if landuse else 0,
                pbb.get('tax_impact', {}).get('total_tax_increase_annual', 0) if pbb else 0,
                0 # Sum below
            ]
        }
        
        # Calculate sum excluding string (period)
        total_p = summary_data['Nilai'][1]
        total_l = summary_data['Nilai'][2]
        total_b = summary_data['Nilai'][3]
        summary_data['Nilai'][4] = total_p + total_l + total_b
        
        df = pd.DataFrame(summary_data)
        df.to_excel(writer, sheet_name='Ringkasan Eksekutif', index=False)
        
        # Formatting later could be added here (width, currency style)

    def _create_parking_sheet(self, writer, df, years_info):
        """
        Create 3-way table for Parking
        """
        if df.empty:
            return

        # Pivot: Revenue by Admin Area & Type
        pivot_rev = pd.pivot_table(
            df,
            index=['Kecamatan', 'Kelurahan', 'Lingkungan'],
            columns=['parking_type'],
            values=['revenue_annual', 'estimated_capacity', 'area_m2'],
            aggfunc='sum',
            fill_value=0
        )
        
        pivot_rev.to_excel(writer, sheet_name='Analisis Parkir')
        
        # Detail Sheet - Business Focused
        df['Tahun Analisis'] = years_info.get('end', '2025') if years_info else '2025'
        
        # Add Google Earth Link
        df['Link Validasi Earth'] = df.apply(lambda row: f"https://earth.google.com/web/search/{row['lat']},{row['lon']}", axis=1)
        
        # Renaissance Columns
        df_display = df[['Tahun Analisis', 'Kecamatan', 'Kelurahan', 'Lingkungan', 'parking_type', 'area_m2', 'estimated_capacity', 'revenue_annual', 'Link Validasi Earth']]
        df_display.columns = ['Tahun', 'Kecamatan', 'Kelurahan', 'Lingkungan', 'Jenis Parkir', 'Luas Area (m2)', 'Kapasitas (Unit)', 'Potensi (Rp/Tahun)', 'Link Validasi Earth']
        
        df_display.to_excel(writer, sheet_name='Data Detail Parkir', index=False)

    def _create_landuse_sheet(self, writer, df, years_info):
        """
        Create 3-way table for Land Use
        """
        if df.empty:
            return
            
        df['change_type'] = df['from_class'] + ' -> ' + df['to_class']
        
        pivot = pd.pivot_table(
            df,
            index=['Kecamatan', 'Kelurahan', 'Lingkungan'],
            columns=['change_type'],
            values=['area_m2', 'estimated_pbb'],
            aggfunc='sum',
            fill_value=0
        )
        
        pivot.to_excel(writer, sheet_name='Alih Fungsi Lahan')
        
        # Detail Sheet - Business Focused
        df['Tahun Perubahan'] = f"{years_info.get('start')} - {years_info.get('end')}" if years_info else "Periode Analisis"
        
        # Recommendation logic
        def get_recommendation(row):
            if row['priority'] == 'HIGH':
                return 'SEGERA VERIFIKASI LAPANGAN (Potensi Pajak Tinggi)'
            elif row['priority'] == 'MEDIUM':
                return 'Jadwalkan Pemeriksaan Rutin'
            return 'Monitor via Sistem'
            
        df['Rekomendasi Tindak Lanjut'] = df.apply(get_recommendation, axis=1)
        
        # Add Google Earth Link
        # Needs lat/lon which should be in 'lat', 'lon' columns from _enrich_with_admin_info via data_list keys
        # _enrich_with_admin_info preserves original columns
        df['Link Validasi Earth'] = df.apply(lambda row: f"https://earth.google.com/web/search/{row['lat']},{row['lon']}" if 'lat' in row and 'lon' in row else "-", axis=1)
        
        # Select business columns only
        df_display = df[[
            'Tahun Perubahan', 'Kecamatan', 'Kelurahan', 'Lingkungan', 
            'change_type', 'area_m2', 'estimated_pbb', 'Rekomendasi Tindak Lanjut', 'Link Validasi Earth'
        ]]
        
        df_display.columns = [
            'Periode Perubahan', 'Kecamatan', 'Kelurahan', 'Lingkungan',
            'Jenis Perubahan', 'Luas Area (m2)', 'Potensi PBB (Rp)', 'Rekomendasi BAPENDA', 'Link Validasi Earth'
        ]
            
        df_display.to_excel(writer, sheet_name='Data Detail Alih Fungsi', index=False)

    def _create_pbb_sheet(self, writer, df, years_info):
        """
        Create 3-way table for PBB
        """
        if df.empty:
            return
            
        # Simplification: Categorize change
        def categorize(row):
            if row['height_increase'] > 0: return 'Penambahan Tingkat'
            return 'Perluasan Area'
            
        df['kategori_perubahan'] = df.apply(categorize, axis=1)
        
        pivot = pd.pivot_table(
            df,
            index=['Kecamatan', 'Kelurahan', 'Lingkungan'],
            columns=['kategori_perubahan'],
            values=['tax_increase', 'area_increase', 'file_verification_needed'], # Using count for verification needed
            aggfunc={'tax_increase': 'sum', 'area_increase': 'sum', 'file_verification_needed': 'count'},
            fill_value=0
        )
        
        pivot.to_excel(writer, sheet_name='Monitoring PBB')
        
        # Detail Sheet - Business Focused
        df['Tahun Deteksi'] = years_info.get('end', '-') if years_info else '-'
        df['Keterangan'] = df.apply(lambda x: f"Luas awal {x['old_area']}m2 menjadi {x['new_area']}m2" if x['area_increase'] > 0 else f"Penambahan tinggi {x['height_increase']}m", axis=1)
        
        # Add Google Earth Link
        df['Link Validasi Earth'] = df.apply(lambda row: f"https://earth.google.com/web/search/{row['lat']},{row['lon']}", axis=1)
        
        df_display = df[[
            'Tahun Deteksi', 'Kecamatan', 'Kelurahan', 'Lingkungan',
            'kategori_perubahan', 'Keterangan', 'area_increase', 'tax_increase', 'Link Validasi Earth'
        ]]
        
        df_display.columns = [
            'Tahun', 'Kecamatan', 'Kelurahan', 'Lingkungan',
            'Jenis Perubahan', 'Deskripsi Fisik', 'Penambahan Luas (m2)', 'Kenaikan PBB (Rp)', 'Link Validasi Earth'
        ]
        
        df_display.to_excel(writer, sheet_name='Data Detail PBB', index=False)
